"use server";

import { openai } from "../openai";
import { getContext } from "./rag.actions";
import { getGirlById } from "./girl.actions";

export async function generateWingmanReply(girlId: string, userMessage: string) {
  try {
    // 1. Fetch Girl Details
    const girl = await getGirlById(girlId);

    // 2. Fetch Context (RAG)
    const contextMessages = await getContext(girlId, userMessage);
    const contextString = JSON.stringify(contextMessages);

    // 3. Construct System Prompt
    const systemPrompt = `
You are "The Wingman", an expert dating coach and master of female psychology.
Your Goal: Help the user ("The Man") hook up with the girl ("${girl.name}").
Details about her: ${girl.vibe || "Unknown"}. Status: ${girl.relationshipStatus}.

Instructions:
1. Analyze the conversation context provided.
2. Provide a DIRECT, UNCENSORED, and FLIRTY reply that the user should send.
3. Explain WHY this reply works (briefly) based on psychology.
4. Support Arabic dialects (Egyptian, Levantine, Gulf) if the user or girl speaks them.
5. Be cool, confident, and not desperate.

Context from previous messages:
${contextString}
`;

    // 4. Call LLM
    if (process.env.OPENAI_API_KEY === "dummy-key" && !process.env.OPENAI_BASE_URL) {
       return {
         reply: `(Mock Wingman): Tell her "You have a vibe that I can't quite put my finger on, but I like it."`,
         explanation: "It's mysterious and complimentary without being too eager."
       };
    }

    const completion = await openai.chat.completions.create({
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: `She just said/I want to say: "${userMessage}". What should I say?` },
      ],
      model: "gpt-4o",
    });

    const aiContent = completion.choices[0]?.message?.content || "Error: No response from AI.";

    return {
      reply: aiContent,
      explanation: "Generated by AI based on context."
    };

  } catch (error) {
    console.error("Wingman Error:", error);
    return {
        reply: "Error generating reply.",
        explanation: "Something went wrong with the AI."
    };
  }
}

export async function generateResponseImage(prompt: string) {
  try {
    if (process.env.OPENAI_API_KEY === "dummy-key" && !process.env.OPENAI_BASE_URL) {
        return "https://via.placeholder.com/1024x1024.png?text=Mock+AI+Image";
    }

    const response = await openai.images.generate({
      model: "dall-e-3",
      prompt: prompt,
      n: 1,
      size: "1024x1024",
    });

    // Check if data exists and has length
    if (response.data && response.data.length > 0) {
        return response.data[0].url;
    }
    return null;
  } catch (error) {
    console.error("Image Gen Error:", error);
    return null;
  }
}
